### ISSUE TITLE
Proj6 Customer Feedback

### ISSUE THREAD

**Issue by AlyssaRicketts** [cnhguy/FootPrint#35]
Your project document is very well done. Again, I appreciate the detail in the architecture and implementation section. My major comments include your figures throughout your document. As mentioned last week, I think it would be helpful to the reader if you reference your figures in the text, to better understand where they fit in. Also, I notice that your first figure in the document is labeled as “Figure 1.2”. Should this be 1.1, and the following figures updated accordingly? Additionally, you have the word “GUI’s” on its own line before figure 1.3. However, since you removed your “interactive gui” diagram from last week, and now only have one gui diagram, I think this line doesn’t make much sense and could just be removed. Finally, I don’t think that figure 1.4 makes sense where it is currently placed. Your “Performance Experiment” section uses future tense (i.e. “we WILL run….”, “we WILL measure…”, etc.). But then immediately after this you present a graph that makes it look as though you have already in fact done these tasks. I would change the tense you use to now instead be past tense, as well as again adding a reference to this figure in the text. Additionally, I think this graph should be in the “initial results” section, as well as should be discussed. What does this graph show? How does it support or revoke your hypotheses? Is a few ms actually a substantial difference?

When reproducing your experimental tests, there was some confusion. Your README.md states “On the repository page, select clone or download and copy the link provided.” I went ahead and cloned the FootPrintTest. However, you say to change the file name on line 74, and then “Click on the FootPrint icon”, but I do not have a FootPrint icon present in my IntelliJ IDE. I remember that you needed to use gradle and build the project for it to launch a new IntelliJ window that I could see the icon in, but it wasn’t clear how I could do this again since the FootPrintTest folder has no gradle files, so the gradle tab wasn’t even a present option. Should the FootPrint tools itself first be built and launched (a new window pops up), and then FootPrintTest should be imported into THIS newly launched workspace? Because it’s confusing since you also say to run ‘./creategraph.sh’ from the FootPrintTest directory and the bar chart will be produced in the root directory of FootPrint, but you have not established what the relationship between those two directories should be. I did follow my intuition and built the original repository using gradle to launch a new window, and then I was able to import FootPrintTest into this new workspace, where I DID have a FootPrint icon. However, setting a breakpoint at line 55 and clicking the FootPrint icon did not output anything to my FootPrint.txt. Additionally, it isn’t clear which FootPrint icon you are talking about pressing: the one labeled “FootPrintDebug” at the top right or “FootPrint” at bottom right. I presumed the FootPrintDebug, but I tried both and neither output anything to FootPrint.txt.

Barchart.pdf was exported into the root directory of ‘FootPrintTest’ folder when I ran ./creategraph.sh from the root directory of ‘FootPrintTest’ as instructed, rather than the root directory of ‘FootPrint’ as stated in the testing user manual. Besides this discrepancy, my graph also did not match yours since I wasn’t able to get output into FootPrint.txt.

Launching your plugin using the runIDE gradle option opens the new IntelliJ workspace as IntelliJ Community Edition rather than  IntelliJ Ultimate Edition, even though that is the version of IntelliJ that I have. Thus, even though I successfully installed Chronon in my main IntelliJ workspace, when I runIDE on the project to open the workspace where I will get a FootPrint icon, I now no longer have a Chronon icon in this workspace view, and cannot install that plugin into this workspace either since it isn’t available on IntelliJ Community Edition.

I think it is a smart decision to push user testing until your team feels that there is something worth demonstrating and testing on other users. However, don’t forget how useful continuous feedback can be! Even if what you have now is very limited, it can still be valuable to receive input early on.

Other than these points, evaluating your proposal as a customer again seems very promising. You addressed the other feedback given this week, and I can tell that you have continued to put thought into the complex problems of running this on top of the existing IntelliJ debugger architecture, extracting data during suspension, and tracking changes.

Criteria | Score
-- | --
The report or the README contains instructions to reproduce the initial results. | 1 / 1
The initial results are reproducible. | 1 / 3
The report has a discussion of the results. | 1 / 2
The report expands on the methodology and is complete. | 1 / 1
The schedule is updated and there is a reasonable discussion on why it changed. | 1 / 1
The user manual is updated. | 2 / 2

**Comment by hangbuiii** [comment]
Hi Alyssa,

Thanks for your thorough feedback for this week! We apologize for the confusion. The directions for running our experiment was written with the idea of a completed FootPrint product in mind (when it has already been shipped and deployed so you can install it onto IntelliJ). We were under the impression that the user just had to reproduce our barchart in FootPrintTest with no further work on their part, and it looks like you were able to do so by running ./creategraph.sh. But thanks for noting your confusion and we will keep that in mind for future references!

Best,
FootPrint Team
