### ISSUE TITLE
Proj7 Customer Feedback

### ISSUE THREAD

**Issue by pujaram** [cnhguy/FootPrint#49]
The overall organization of the report is sensible. There is a flow to the entire document in terms of the way the sections are ordered. However, sometimes diagrams are inserted into the document at the beginning of sections before they are discussed which makes the reader try to understand the diagram or chart before having any context of the information. The introduction does explain the problem and subsequently the solution that they are proposing. They describe the current approaches as well as their own, and how their approach is better than the current approaches in terms of their goal and audience. The technical details are discussed under the architecture and implementation section of their report. They discuss the different components in their architecture diagram and how these components interact with one another. 

The report points to an external link to a separate repository to describe how to reproduce the tests and graphs for their project. There is not a way to reproduce the survey results, however, although they state that the charts were created by SurveyMonkey. There should be a short description on how to use SurveyMonkey to produce these graphs, rather than just stating that this website created the graphs. It might be useful to create bar graphs that show how many users gave which rating rather than displaying the average in the visual charts in order to show the distribution of user reviews. There could be much more discussion of the results in text as well. Another aspect that could be incorporated is how they will use the feedback to change the tool and how these changes will improve the tool. 

They discuss related work in the current approaches section and include references throughout this section. There is a variety of related work and they briefly discuss each of these tools and their functionalities. Every tool has a reference cited, which makes the discussion of related work much more reputable. Overall, your final report is well written and provides a lot of information to anyone trying to understand the purpose, implementation, and results of FootPrint.

Criteria | Score
-- | --
Overall organization is sensible | 1
Introduction motivates the problem and describes the approach | 1
The technical details of the approach are well-described | 1
The report contains a clear description of a reproducable methodology | 0.5
Results are presented clearly and described in text | 0.5
The report describes related work and contains academic references | 1
**Total:** | 5/6

**Comment by audreytnt** [comment]
hi thanks for the feedback! regarding SurveyMonkey, only the person who made the survey can view and edit the automatically generated graphs so we can't give instructions on how to reproduce them.
